config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { invitations: 'invitations' }
  resources :project_details
  resources :projects do
    resources :users do
      resources :project_details, only: %i[new create]
    end
  end

  resources :projects do
    resources :bugs do
      put 'bug_assignment'
      put 'mark_complete'
    end
    resources :project_users, only: [:index]
    resources :project_details, only: [:index]
  end
end

app/views/share/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-primary'>
  <a class='navbar-brand' href='#'>
    Bugzilla
  </a>
  <div class='collapse navbar-collapse' id='navbarSupportedContent'>
    <ul class='navbar-nav mr-auto'>
      <% if user_signed_in? %>
            <% if current_user.role == 'Manager' %>
                    <li class='nav-item active'>
                      <%= link_to 'DashBoard', root_path, :method => :get ,  class:'nav-link active' %>
                    </li>
                    <li class='nav-item active'>
                      <%= link_to 'Projects', projects_path, :method => :get ,  class:'nav-link active' %>
                    </li>
                    <li class='nav-item active'>
                      <%= link_to 'Add Users', new_user_invitation_path, :method => :get ,  class:'nav-link active' %>
                    </li>
    </ul>
              <div class='nav-item dropdown bg-faded'>
                <a class='nav-link dropdown-toggle text-light link-light' href='#' id='navbarDropdown1' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                  <%= current_user.name %>
                </a>
                <div class='dropdown-menu' aria-labelledby='navbarDropdown1'>
                  <a class='dropdown-item' href='#'>
                    <%= current_user.role %>
                  </a>
                  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete ,  class:'dropdown-item' %>
                </div>
              </div>
            <%end%>
            <% if current_user.role == 'Developer' %>
              <li class='nav-item active'>
                <%= link_to 'DashBoard', root_path, :method => :get ,  class:'nav-link active' %>
              </li>
              <li class='nav-item active'>
                <%= link_to 'Projects', projects_path, :method => :get ,  class:'nav-link active' %>
              </li>
    </ul>
              <div class='nav-item dropdown bg-faded'>
                <a class='nav-link dropdown-toggle text-light link-light' href='#' id='navbarDropdown1' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                <%= current_user.name %>
                </a>
                <div class='dropdown-menu' aria-labelledby='navbarDropdown1'>
                  <a class='dropdown-item' href='#'><%= current_user.role %></a>
                  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete ,  class:'dropdown-item' %>
                </div>
              </div>
           <%end%>
           <% if current_user.role == 'QA' %>
               <li class='nav-item active'>
                 <%= link_to 'DashBoard', root_path, :method => :get ,  class:'nav-link active' %>
               </li>
               <li class='nav-item active'>
                 <%= link_to 'All Projects', projects_path, :method => :get ,  class:'nav-link active' %>
               </li>
      </ul>
             <div class='nav-item dropdown bg-faded'>
               <a class='nav-link dropdown-toggle text-light link-light' href='#' id='navbarDropdown1' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                 <%= current_user.name %>
               </a>
               <div class='dropdown-menu' aria-labelledby='navbarDropdown1'>
                 <a class='dropdown-item' href='#'><%= current_user.role %></a>
                   <%= link_to 'Sign out', destroy_user_session_path, :method => :delete ,  class:'dropdown-item' %>
               </div>
             </div>
            <%end%>
      <% end %>
  </div>
</nav>