config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { invitations: 'invitations' }
  resources :project_details
  resources :projects do
    resources :users do
      resources :project_details, only: %i[new create]
    end
  end

  resources :projects do
    resources :bugs do
      put 'bug_assignment'
      put 'mark_complete'
    end
    resources :project_users, only: [:index]
    resources :project_details, only: [:index]
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    return unless user_signed_in?
  end
end

app/views/home/all_users.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>
<p class= 'h2 text-center m-3'>ALL Users</p>
<table class = 'table'>
  <tr>
    <th  scope="col">
      Email
    </th>
     <th  scope="col">
      Name
    </th>
     <th  scope="col">
      Role
    </th>
  </tr>
  <% @users.each do |user| %>
    <% if user.role == 'Developer' ||  user.role == 'QA' %>
      <tr scope="row">
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.role %>
        </td>
        <td>
          <%= link_to 'Add', project_user_project_details_path(params[:project_id], user.id), method: :post , class: "btn btn-primary" %>
        </td>
      </tr>
    <%end%>
  <%end%>
</table>
<%= link_to '<- Back', projects_path, class: 'btn btn-primary m-3' %>

app/views/home/index.html.erb
<div class="pt-5 ">
  <div class="row">
    <% if current_user.role == 'Manager' %>
      <div class="col-md-3 m-1">
         <%= link_to new_project_path do %>
            <div class='card'>
               <div class='card-body container text-center bg-primary'>
                     <i class='fa text-light fa-plus fa-6x view overlay zoom' aria-hidden='true'></i>
                     <h5 class='text-light'>
                        Create New Project
                     </h5>
               </div>
          </div>
         <% end %>
      </div>
    <%end%>
      <% current_user.projects.each do |project| %>

         <% if project.status == 'Active' %>
              <div class="col-md-3 bg-light m-1 pt-2 bg-light ">
                <%= link_to  project_path(project.id), class: "text-decoration-none text-dark" do %>
                 <div class="d-flex justify-content-between">
                    <h4>
                       <%= project.name %>
                    </h4>
                    <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                 </div>
                 <div>
                    <p>
                       <%= project.description %>
                    </p>
                 </div>
                 <div>
                    <p>
                       <%= find_project_bugs(project)%> Bugs
                    </p>
                 </div>
                 <div class="d-flex justify-content-between">
                    <div>
                       <%= project.created_at %>
                    </div>
                    <div class = 'text-danger'>
                       <%= project.due_date %>
                    </div>
                   <div>
                       <i class="fa fa-circle" aria-hidden="true"></i>
                    </div>
                 </div>
                 <%end%>
              </div>

         <%end%>
      <% end %>
  </div>
</div>