config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { invitations: 'invitations' }
  resources :project_details
  resources :projects do
    resources :users do
      resources :project_details, only: %i[new create]
    end
  end

  resources :projects do
    resources :bugs do
      put 'bug_assignment'
      put 'mark_complete'
    end
    resources :project_users, only: [:index]
    resources :project_details, only: [:index]
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :project_details, dependent: :destroy
  has_many :bugs,  dependent: :destroy
  has_many :users, through: :project_details, dependent: :destroy
  validates :name, :description, :status, :due_date, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 10..40 }
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    user = current_user
    @projects = current_user.role == 'QA' ? Project.all : user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    authorize @project

    if @project.save
      ProjectDetail.create(user_id: current_user.id, project_id: @project.id, project_creator: current_user.id)
      redirect_to projects_path, info: 'Project Created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    authorize @project

    if @project.update(project_params)
      redirect_to projects_path, info: 'Project Updated Sucessfuly'
    else
      redirect_to projects_path, danger: 'Unabled to update project'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project

    if @project.destroy
      redirect_to projects_path, info: 'Project Dleted Sucessfuly'
    else
      redirect_to projects_path, danger: 'Unabled to delete project'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :status, :due_date)
  end
end

app/helpers/project_helper.rb
# frozen_string_literal: true

module ProjectHelper
  def find_project_manager(name)
    records = name.where(role: 'Manager')
  end

  def find_project_developer(name)
    records = name.where(role: 'Developer')
  end

  def find_project_qa(name)
    records = name.where(role: 'QA')
  end

  def find_project_bugs(name)
    name.bugs.count
  end
end

app/views/projects/_form.html.erb
<%= form_for project do |f| %>
<form>
  <div class="container">
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, class: 'form-control w-50 m-2' %>
    <%= f.label :description, "Description:" %>
    <%= f.text_area :description, class: 'form-control w-50 m-2'  %>
    <%= f.label :status, "Status: " %>
    <%= f.select :status, options_for_select({Active: 'Active', Completed: 'Completed', Cancled: 'Cancled'}), {}, class: "form-control w-50 m-2" %>

    <%= f.label :due_date, "Due Date" %>
    <%= f.date_field :due_date, class: 'form-control w-50 m-2' %>
    <%= link_to '<- Back', projects_path, class: "btn btn-primary" %>
    <%= f.submit class: "btn btn-primary" %>
  <div>
</form>
<% end %>

app/views/projects/edit.html.erb
<h2 class = 'h2 m-3'>Update</h2>
<%= render partial: 'form', locals: {project: @project} %>

app/views/projects/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>
<table class = 'table'>
   <tr>
      <th scope="col">
         Porject Name
      </th>
      <th scope="col">
         Status
      </th>
      <th scope="col">
         Deadline
      </th>
      <td colspan="5" class='text-center'>Operations</td>
   </tr>
   <% @projects.each do |project| %>
      <tr scope="row">
         <td>
            <%= project.name %>
         </td>
         <td>
            <%= project.status %>
         </td>
         <td>
             <%= project.due_date %>
         </td>
         <td>
            <%= link_to 'Show', project_path(project.id), class: 'btn btn-info' %>
         </td>
         <% if current_user.role == 'Manager' %>
            <td>
               <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-success' %>
            </td>
            <td>
               <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
            <td>
               <%= link_to 'Add Devs / QA to project', project_users_path(project.id), class: 'btn btn-primary' %>
            </td>
         <% end %>
         <td>
            <%= link_to 'Bugs', project_bugs_path(project.id), class: 'btn btn-dark' %>
         </td>
      </tr>
   <% end %>
</table>

app/views/projects/new.html.erb
<h2 class= 'text-center h2 m-5'>Add projects</h2>
  <% if @project.errors.any?%>
    <h2>
      Errors
    </h2>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li class= 'alert-danger'>
          <%= message %>
        </li>
      <%end%>
    </ul>
  <%end%>
<%= render partial: 'form', locals: {project: @project} %>

app/views/projects/project_users.html.erb
<p class= 'h3 text-center' > Developers </p>
<table class= 'table'>
   <tr>
      <th  scope="col">
         User Email
      </th>
      <th  scope="col">
         User Name
      </th>
      <th  scope="col">
         Role
      </th>
      <th scope="colspan text-center">
         Operations
      </th>
   </tr>
   <% @project.project_details.each do |project_detail| %>
         <tr scope="row">
            <% if project_detail.user.role == 'Developer' %>
               <td>
                  <%= project_detail.user.email %>
               </td>
               <td>
                  <%= project_detail.user.name %>
               </td>
               <td>
                  <%= project_detail.user.role %>
               </td>
               <% if current_user.role == 'Manager' %>
                  <td>
                     <%= link_to 'Remove', destroy_user_path(project_detail.id),method: :delete, class: 'btn btn-danger'%>
                  </td>
               <%end%>
            <%end%>
         </tr>
   <% end %>
</table>
<p class= 'h3 text-center' > QA </p>
<table class= 'table'>
   <tr>
      <th  scope="col">
         User Email
      </th>
      <th  scope="col">
         User Name
      </th>
      <th  scope="col">
         Role
      </th>
      <th scope="colspan text-center">
         Operations
      </th>
   </tr>
   <% @project.project_details.each do |project_detail| %>
      <tr scope="row">
         <% if  project_detail.user.role == 'QA' %>
            <td>
               <%= project_detail.user.email %>
            </td>
            <td>
               <%= project_detail.user.name %>
            </td>
            <td>
               <%= project_detail.user.role %>
            </td>
            <% if current_user.role == 'Manager' %>
               <td>
                  <%= link_to 'Remove', destroy_user_path(project_detail.id),method: :delete, class: 'btn btn-danger'%>
               </td>
            <%end%>
         <%end%>
      </tr>
   <% end %>
</table>

app/views/projects/show.html.erb
<p class = 'h3 text-center'>
  Show Project Details
</p>
<div class="row p-5">
  <div class="col-md-6" >
    <h5>
      Name:
    </h5>
    <p>
      <%= @project.name %>
    </p>
    <h5>
      Description:
    </h5>
    <p>
      <%= @project.description %>
    </p>
    <h5>
      Status:
    </h5>
    <p>
      <%= @project.status %>
    </p>
    <h5>
      Created Date:
    </h5>
    <p>
      <%= @project.created_at %>
    </p>
  </div>
  <div class="col-md-6" >
    <h5>
      Project Manager:
    </h5>
    <% find_project_manager(@project.users).each do |record| %>
      <p>
        <%= record.name %>
      </p>
    <%end%>
    <h5>
      Total Developers:
    </h5>
    <p>
      <%= link_to find_project_developer(@project.users).count , project_project_details_path(@project.id)%>
    </p>
    <h5>
      Total QAs:
    </h5>
    <p>
      <%= link_to find_project_qa(@project.users).count , project_project_details_path(@project.id) %>
    </p>
    <h5>
      Total bugs:
    </h5>
    <p>
      <%= link_to find_project_bugs(@project), project_bugs_path(@project.id) %> Bugs
    </p>
    <h5>
      Deadline:
    </h5>
    <p class='text-danger'>
      <%= @project.due_date.strftime %>
    </p>
  </div>
</div>
<%=link_to '<- Back', projects_path, class: 'btn btn-primary btn-lg m-5'%>