config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { invitations: 'invitations' }
  resources :project_details
  resources :projects do
    resources :users do
      resources :project_details, only: %i[new create]
    end
  end

  resources :projects do
    resources :bugs do
      put 'bug_assignment'
      put 'mark_complete'
    end
    resources :project_users, only: [:index]
    resources :project_details, only: [:index]
  end
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_one_attached :bug_image
  validates :title, :status, :bug_type, :project_id, :deadline, :bug_image, presence: true
  validates :title, uniqueness: true
  validates :title, length: { in: 15..30 }
  validate  :check_date, :image_type
  # validate :image_type

  private

  def check_date
    errors.add(:deadline, 'enter today or later date') if !deadline.nil? && (deadline < Date.today)
    errors.add(:bug_image, 'is missing!') if bug_image.attached? == false
  end

  def image_type
    if bug_image.attached? && !bug_image.content_type.in?(%('bug_image/jpg bug_image/png'))
      errors.add(:bug_image, 'needs to be a jpg or png!')
    end
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  before_action :set_project, only: %i[new create index show destory]
  before_action :set_bug, only: %i[edit update show destory bug_assignment mark_complete]

  def index
    @bugs = @project.bugs
  end

  def new
    @bugs = @project.bugs.build
  end

  def create
    @bugs = @project.bugs.build(bug_params)
    authorize @bugs
    if @bugs.save

      redirect_to project_bugs_path(@bugs.project_id), info: 'Bug Created Sucessfuly'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bug
  end

  def update
    @bug.bug_assign = current_user.name
    authorize @bugs

    if @bug.save
      redirect_to project_bugs_path(@bug.project_id), info: 'Assign bug Sucessfuly'
    else
      redirect_to project_bugs_path(@bug.project_id), danger: 'Unabled to assign bug'
    end
  end

  def bug_assignment
    @bug.bug_assign = current_user.name
    if @bug.save
      redirect_to project_bugs_path(@bug.project_id), info: 'Assign bug tour self Sucessfuly'
    else
      redirect_to project_bugs_path(@bug.project_id), danger: 'Not assign bug'
    end
  end

  def mark_complete
    @bug.completion_status = true if @bug.bug_assign == current_user.name
    if @bug.save
      redirect_to project_bugs_path(@bug.project_id), info: 'Bug marks as completed Sucessfuly'
    else
      redirect_to project_bugs_path(@bug.project_id), danger: 'Not Completed'
    end
  end

  private

  def bug_params
    params.require(:bug).permit(:title, :description, :bug_image, :bug_type, :status, :deadline, :user_id)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_bug
    @bug = params[:id].nil? ? Bug.find(params[:bug_id]) : Bug.find(params[:id])
  end
end

app/views/bugs/_form.html.erb
<%= form_for [project ,bugs] do |bug| %>
  <form>
    <div class="container">
      <%= bug.label :title, "Title: " %>
        <%= bug.text_field :title, class: 'form-control w-50 m-2'  %>
        <%= bug.label :description, "Description: " %>
        <%= bug.text_area :description, class: 'form-control w-50 m-2'  %>
        <%= bug.label :bug_image, "Bug Image (.png / .jpg)" %>
        <%= bug.file_field :bug_image, class: 'form-control-file w-50 m-2' %>
        <%= bug.label :bug_type, "Type: " %>
        <%= bug.select :bug_type, options_for_select({ Feature: 'Feature', Bug: 'Bug' }), {}, class: "form-control w-50 m-2"  %>
        <%= bug.label :status, "Status: " %>
        <%= bug.select :status, options_for_select({ New: 'New', Started: 'Started', Completed: 'Completed' }), {}, class: "form-control w-50 m-2"  %>
        <%= bug.label :deadline, "Deadline" %>
        <%= bug.date_field :deadline , class: 'form-control-file w-50 m-2' %>
        <%= bug.hidden_field :user_id, value: current_user.id %>
        <%= link_to '<- Back', project_bugs_path(project.id), class: "btn btn-primary" %>

        <%= bug.submit class: "btn btn-primary" %>
    </div>
  </form>
<% end %>

app/views/bugs/edit.html.erb
<h1>Edit Bug</h1>
<%= render partial: 'form', locals: {project: @project, bugs: @bug} %>

app/views/bugs/index.html.erb
<% if current_user.role == 'QA' %>
  <%= link_to 'Add Bug', new_project_bug_path, class: 'btn btn-primary mt-3 ml-3 mb-2' %>
<% end %>

<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>
<table class = 'table'>
  <tr>
    <th scope= 'col'>
      Title
    </th>
    <th scope= 'col'>
      Status
    </th>
    <th scope= 'col'>
      Deadline
    </th>
    <th scope= 'col'>
      Bug
    </th>
    <th scope= 'col'>
      Completion Status
    </th>
    <th scope= 'col'>
      Assignment
    </th>
    <th scope='colspan'>
    </td>
  </tr>
  <% @bugs.each do |bug| %>
    <tr  scope= 'row'>
      <td>
        <%= bug.title %>
      </td>
      <td>
        <%= bug.status %>
      </td>
      <td>
        <%= bug.deadline %>
      </td>
      <td>
        <%= image_tag bug.bug_image, width: '100px' %>
      </td>
      <td>
        <% if bug.completion_status == true %>
          <i class = 'fa fa-check text-success'></i>
          <% else %>
             <i class = 'fa fa-check'></i>
        <% end %>
      </td>
      <td>
        <% if current_user.role == 'Manager' || current_user.role == 'QA'  %>
          <%=  bug.bug_assign.blank? ? 'Not Assigned' : 'Assigned' %>
        <% end %>
        <% if current_user.role == 'Developer'%>
          <% if bug.bug_assign.blank? %>
            <%= link_to 'Bug Assignment', project_bug_bug_assignment_path(bug.project_id, bug.id), method: :put, class: 'btn btn-primary' %>
            <% else %>
              Assigned
          <% end %>
        <% end %>

      </td>
      <td>
      <%= link_to 'Show', project_bug_path(params[:project_id], bug.id), class: 'btn btn-info' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/bugs/new.html.erb
<p class='h2 text-center m-3'>
  Create Bug
</p>
<% if @bugs.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@bugs.errors.count, "error") %>
      prohibited this record from being saved:
    </h2>
    <ul class= 'text-danger'>
      <% @bugs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: 'form', locals: {project: @project, bugs: @bugs} %>

app/views/bugs/show.html.erb
<p class = 'h3 text-center'>
  Show Bug Details
</p>
<div class="row m-2">
  <div class="container col-md-4" >
    <h5>
      Title
    </h5>
      <p>
        <%= @bug.title %>
      </p>
    <h5>
      Description
    </h5>
      <p>
        <%= @bug.description %>
      </p>
      <h5>
      Created By
    </h5>
      <p>
        <%= @bug.user.name %> QA
      </p>
      <h5>
      Assigned to
    </h5>
      <p>
        <%=  @bug.bug_assign.blank? ? 'Not Assigned' : @bug.bug_assign %>
      </p>
  </div>
  <div class="container col-md-4" >
    <h5>
      Bug Type
    </h5>
    <%= @bug.bug_type %>
    <h5>
      Status
    </h5>
    <%= @bug.status %>
    <h5>
      Deadline
    </h5>
    <%= @bug.deadline %>
  </div>
  <div class="container col-md-4" >
    <%= image_tag @bug.bug_image, width: '400px' %>
  </div>
</div>
<%= link_to '<- Back', project_bugs_path(@bug.project_id), class: 'btn btn-primary' %>
<% if current_user.role == 'Developer' %>
  <% if current_user.name == @bug.bug_assign && @bug.completion_status == false %>
    <%= link_to 'Mark as completed', project_bug_mark_complete_path( @bug.project_id , @bug.id), method: :put, class: 'btn btn-primary' %>
  <% end %>
<% end %>